language: python

python: "3.6"

cache: pip

jobs:
  include:
    - stage: test
      language: python
      cache: pip
      python: "3.6"
      install: pip install .
      script: pytest

    - stage: test
      language: python
      # Python 3.7 still not available in usual distro
      sudo: required
      dist: xenial
      python: "3.7"
      install: pip install .
      script: pytest

    - stage: build and deploy docs
      if: branch = docs
      before_install:
        - nvm install 8
        - nvm use 8
      install: npm install
      script: npm run docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs/.vuepress/dist

    - stage: deploy to test pypi
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $TEST_PYPI_USERNAME
          password: $TEST_PYPI_PASSWORD
          server: https://test.pypi.org/legacy/
          on:
            branch: release/test

    - stage: deploy to pypi
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
