language: python

python: "3.6"

cache: pip

jobs:
  include:
    - stage: test
      if: branch != release/docs
      language: python
      cache: pip
      python: "3.6"
      install:
        - pip install ".[files,sessions]"
        - pip install -U pytest pytest-asyncio codecov pytest-cov
      script: pytest --cov=./
      after_success: codecov

    - stage: test
      if: branch != release/docs
      language: python
      # Python 3.7 still not available in usual distro
      sudo: required
      dist: xenial
      python: "3.7"
      install:
        - pip install ".[files,sessions]"
        - pip install -U pytest pytest-asyncio
      script: pytest

    - stage: build and deploy docs
      if: branch = release/docs
      before_install:
        - nvm install 8
        - nvm use 8
      install:
        - pip install .
        - pip install "pydoc-markdown<2.0.5"
        # ^ See: https://github.com/NiklasRosenstein/pydoc-markdown/pull/78
        - npm install --only=dev
      script:
        - pydocmd generate
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        repo: bocadilloproject/bocadilloproject.github.io
        github-token: $GITHUB_TOKEN
        target-branch: master
        local-dir: docs/.vuepress/dist
        on:
          branch: release/docs

    - stage: deploy to test pypi
      if: branch = release/test
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $TEST_PYPI_USERNAME
          password: $TEST_PYPI_PASSWORD
          server: https://test.pypi.org/legacy/
          on:
            branch: release/test

    - stage: deploy to pypi
      if: tag IS present
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
