language: python
dist: xenial
python: "3.6"

jobs:
  include:
    - stage: test
      python: "3.6"
      script: invoke ci

    - stage: test
      python: "3.7"
      script: invoke ci
      after_success: codecov

    - stage: docs
      if: branch = release/docs
      before_install:
        - nvm install 10
        - nvm use 10
        - npm install
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        repo: bocadilloproject/bocadilloproject.github.io
        github-token: $GITHUB_TOKEN
        target-branch: master
        local-dir: docs/.vuepress/dist
        on:
          branch: release/docs

    - stage: release
      if: tag IS present
      install: skip
      script: skip
      deploy:
        provider: pypi
        distributions: "sdist bdist_wheel"
        username: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        on:
          tags: true
